name: crud_o_core
description: "A new Flutter package project."
version: 0.0.1
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

environment:
  sdk: ^3.5.1
  flutter: ">=1.17.0"

dependencies:
  animated_custom_dropdown:
    git: https://github.com/Murkrow02/flutter-custom-dropdown
#  animated_custom_dropdown:
#    path: ../flutter-custom-dropdown
  animated_search_bar: ^2.7.2
  audioplayers: ^6.4.0
  bot_toast: ^4.1.3
  calendar_date_picker2: ^2.0.0
  collection: ^1.18.0
  custom_sliding_segmented_control: ^1.8.4
  datetime_picker_formfield_new: ^2.1.0
  equatable: ^2.0.5
  event_bus: ^2.0.1
  file_picker: 8.1.4
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.6
  flutter_image_compress: ^2.3.0
  futuristic: ^0.2.0
  haptic_feedback: ^0.5.1+1
  http: ^1.2.2
  image_picker: ^1.1.2
  interact_cli: ^2.4.0
  intl: ^0.19.0
  logger: ^2.4.0
  multi_image_picker_view: ^1.1.0
  permission_handler: ^11.3.1
  pluto_grid_plus: ^8.4.2
  provider: ^6.1.2
  shared_preferences: ^2.3.3
  smooth_counter: ^0.2.0
  waveform_recorder: ^1.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # To add assets to your package, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  #
  # For details regarding assets in packages, see
  # https://flutter.dev/to/asset-from-package
  #
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # To add custom fonts to your package, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts in packages, see
  # https://flutter.dev/to/font-from-package
